spring:
  application:
    name: dualmongo
  data:
    mongodb:
      core:
        uri: mongodb://coreuser:corepassword@core-mongo:27017/core?authSource=admin
        database: core
      support:
        uri: mongodb://supportuser:supportpassword@support-mongo:27017/support?authSource=admin
        database: support
